[package]
name = "pixelflut"
version = "0.1.0"
authors = ["Max Bruckner <max@maxbruckner.de>"]
edition = "2018"

[dependencies]
rand = "0.8"
serde = {version = "1", features = ["derive"]}
image = "0.24"
ctrlc = "3"
toml = "0.5"
anyhow = "1"
