host = "pixl.gulasch.pw"
port = 1234
connections = 8
style = "Image"
timeout = 300

[dimension]
width = 200
height = 200

[offset]
x = 100
y = 300

[image]
path = "image.jpg"

[fractal]
iterations = 100
active_threshold = 0.0

[fractal.initial_value]
real = -0.6
imag = 0.6

